name: emo_project
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_functions: ^4.4.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.2
  riverpod_annotation: ^2.1.5
  riverpod_generator: ^2.3.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  cached_network_image: ^3.2.3
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/lottie/